<script setup lang="ts">
const boxShadow = 'box-shadow: inset 0 0 10px #0d1117;';
</script>

<template>
  <div class="text-white text-2xl font-bold">
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="kanto">Kanto</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="johto">Johto</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="hoenn">Hoenn</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="sinnoh">Sinnoh</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="unova">Unova</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="kalos">Kalos</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="alola">Alola</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="galar">Galar</router-link>
    </div>
    <div
      class="
        py-2
        my-1
        w-full
        text-left
        pl-5
        bg-darkgray-100
        hover:bg-green-400
        cursor-pointer
      "
      :style="boxShadow"
    >
      <router-link to="all">All Regions</router-link>
    </div>
  </div>
</template>
